import test from "@playwright/test";

test("Create test lead", async({page})=>{
    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.locator("#username").fill("DemoSalesManager")
    await page.locator(".inputLogin").last().fill("crmsfa")
    await page.locator(".decorativeSubmit").click()
    await page.locator(`text='CRM/SFA'`).click()
    await page.waitForTimeout(4000)
    await page.locator(`text='Leads'`).click()
    await page.waitForTimeout(4000)
    await page.locator(`text='Create Lead'`).first().click()
    await page.waitForTimeout(4000)
    await page.locator("#createLeadForm_companyName").first().fill("TestCompany")
    await page.locator("#createLeadForm_firstName").fill("Testfirstname")
    await page.locator("#createLeadForm_lastName").fill("Testlastname")
    await page.waitForTimeout(5000)
    await page.locator("#createLeadForm_personalTitle").fill("TestSalution")
    await page.locator("#createLeadForm_generalProfTitle").fill("TestTile")
    await page.waitForTimeout(5000)
    await page.locator("#createLeadForm_annualRevenue").fill("1000000")
    await page.locator("#createLeadForm_departmentName").fill("Testdepartment")
    await page.locator("#createLeadForm_primaryPhoneNumber").fill("9867543211")
    await page.locator(".smallSubmit").click()
})